Document: slack-desktop
Title: Debian slack-desktop Manual
Author: <insert document author here>
Abstract: This manual describes what slack-desktop is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/slack-desktop/slack-desktop.sgml.gz

Format: postscript
Files: /usr/share/doc/slack-desktop/slack-desktop.ps.gz

Format: text
Files: /usr/share/doc/slack-desktop/slack-desktop.text.gz

Format: HTML
Index: /usr/share/doc/slack-desktop/html/index.html
Files: /usr/share/doc/slack-desktop/html/*.html
